# Use a lightweight Python image
FROM python:3.9-slim

# Set the working directory in the container
WORKDIR /app

# Copy all project files into the container
COPY . /app

# Run the console-based Inventory Management System (IMS) application
CMD ["python", "python.py"]
